#!/bin/sh

TESTCHECKPOINT="parser"

aspfiles=$(ls "./test/$TESTCHECKPOINT")

for file in $aspfiles; do
    java -jar ref-asp.jar "-test$TESTCHECKPOINT" "./test/$TESTCHECKPOINT/$file" > /dev/null 2>&1
    mv "./test/$TESTCHECKPOINT/${file%.asp}.log" "./test/$TESTCHECKPOINT/${file%.asp}-ref.log"

    java -jar asp.jar "-test$TESTCHECKPOINT" "./test/$TESTCHECKPOINT/$file" > /dev/null 2>&1

    diffs="$(diff ./test/$TESTCHECKPOINT/${file%.asp}-ref.log ./test/$TESTCHECKPOINT/${file%.asp}.log)"
    if [ -z "$diffs" ]; then
        echo "\033[0;32mNo differences in file $file\033[0m"
    else
        echo "\033[0;31mFound differences in file $file\033[0m\n $diffs\n\n Stopping execution of tests..."
        rm ./test/$TESTCHECKPOINT/*.log
        exit
    fi
done

rm ./test/$TESTCHECKPOINT/*.log
